
server.port=5252
spring.datasource.url=jdbc:mysql://localhost:3306/food
spring.datasource.username=root
spring.datasource.password=9603065526usha

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
